baseurl = "https://example.com/"  # Include trailing slash
title = "BLEH"
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
 # edit this if you'ld rather use a fork of this repo
theme = "newsroom"
author = "Weru"
canonifyurls = false
[pagination]
  pagerSize = 6

[permalinks]
  pages = ':filename/'

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"
